spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8078

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8079/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId:
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign