spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://git.lug.ustc.edu.cn/291421358/spring-cloud-config.git
          search-paths: respo
          username: 291421358
          password: l291421358

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/