server:
  port: 8080

#mysql
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: ok
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/tzhh/hello/feign/mapper/*.xml
  type-aliases-package: com.tzhh.hello.feign.entity

